default: &default
  adapter: "postgresql"
  encoding: "unicode"
  database: "<%= ENV.fetch('POSTGRES_DB') { 'bycoders' } %>"
  username: "<%= ENV.fetch('POSTGRES_USER') { 'bycoders' } %>"
  password: "<%= ENV.fetch('POSTGRES_PASSWORD') { 'bycoders_password' } %>"
  host: "<%= ENV.fetch('POSTGRES_HOST') { 'postgres' } %>"
  port: "<%= ENV.fetch('POSTGRES_PORT') { 5432 } %>"
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'bycoders' } %>_development

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'bycoders' } %>_test

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'bycoders' } %>_production
